/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Irene, Yushan
 */
public class ManageMyProfileJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;    
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientOrganization patientOrganization;
    private Patient patient;
    /**
     * Creates new form ViewMyProfileJPanel
     */
    public ManageMyProfileJPanel(JPanel userProcessContainer,UserAccount userAccount, PatientOrganization patientOrganization, Enterprise enterprise,EcoSystem ecoSyste) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        this.patientOrganization = (PatientOrganization)patientOrganization;
        this.enterprise = enterprise;
        this.patient=userAccount.getPatient();
        
        nameJTextField.setText(patient.getPatientName());
        patientIDJTextField.setText(String.valueOf(patient.getPatientID()));
        ageJTextField.setText(String.valueOf(patient.getAge()));
        streetAddressJTextField.setText(patient.getStreetAddress());
        cityJTextField.setText(patient.getTown());
        zipCodeJTextField.setText(String.valueOf(patient.getZipCode()));
        emailJTextField.setText(patient.getEmailAddress());
        areaCodeJTextField.setText(String.valueOf(patient.getAreaCode()));
        numberJTextField.setText(String.valueOf(patient.getPhoneNumber()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cityJTextField = new javax.swing.JTextField();
        zipCodeJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();
        numberJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();
        areaCodeJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        patientIDJTextField = new javax.swing.JTextField();
        updateJButton = new javax.swing.JButton();
        streetAddressJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        btnIntegrate = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 196, 122));
        setMaximumSize(new java.awt.Dimension(700, 410));
        setMinimumSize(new java.awt.Dimension(700, 410));
        setPreferredSize(new java.awt.Dimension(700, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cityJTextField.setEnabled(false);
        cityJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityJTextFieldFocusLost(evt);
            }
        });
        add(cityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 183, -1));

        zipCodeJTextField.setEnabled(false);
        zipCodeJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                zipCodeJTextFieldFocusLost(evt);
            }
        });
        add(zipCodeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 183, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setText("Manage My Profile");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 270, -1));

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        nameJTextField.setEditable(false);
        nameJTextField.setEnabled(false);
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 183, -1));

        jLabel2.setText("Age");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        ageJTextField.setEnabled(false);
        ageJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageJTextFieldActionPerformed(evt);
            }
        });
        add(ageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 183, -1));

        numberJTextField.setEnabled(false);
        numberJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberJTextFieldFocusLost(evt);
            }
        });
        add(numberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 106, -1));

        emailJTextField.setEnabled(false);
        emailJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailJTextFieldFocusLost(evt);
            }
        });
        add(emailJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 182, -1));

        areaCodeJTextField.setEnabled(false);
        areaCodeJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaCodeJTextFieldFocusLost(evt);
            }
        });
        add(areaCodeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 50, -1));

        jLabel4.setText("Patient ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        patientIDJTextField.setEditable(false);
        patientIDJTextField.setEnabled(false);
        patientIDJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDJTextFieldActionPerformed(evt);
            }
        });
        add(patientIDJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 183, -1));

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });
        add(updateJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        streetAddressJTextField.setEnabled(false);
        streetAddressJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetAddressJTextFieldFocusLost(evt);
            }
        });
        add(streetAddressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 183, -1));

        jLabel6.setText("Phone Number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel5.setText("Email Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel3.setText("Zip Code");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel7.setText("City/Town");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel8.setText("Street Address");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel10.setText("-");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 10, -1));

        saveJButton.setText("Save");
        saveJButton.setEnabled(false);
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnIntegrate.setText("Integrate");
        btnIntegrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegrateActionPerformed(evt);
            }
        });
        add(btnIntegrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cityJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityJTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextFieldFocusLost

    private void zipCodeJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipCodeJTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeJTextFieldFocusLost

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void ageJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageJTextFieldActionPerformed

    private void numberJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberJTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_numberJTextFieldFocusLost

    private void emailJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailJTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJTextFieldFocusLost

    private void areaCodeJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaCodeJTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_areaCodeJTextFieldFocusLost

    private void patientIDJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDJTextFieldActionPerformed

    private void streetAddressJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetAddressJTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_streetAddressJTextFieldFocusLost

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        
        nameJTextField.setText(patient.getPatientName());
        patientIDJTextField.setText(String.valueOf(patient.getPatientID()));
        ageJTextField.setText(String.valueOf(patient.getAge()));
        streetAddressJTextField.setText(patient.getStreetAddress());
        cityJTextField.setText(patient.getTown());
        zipCodeJTextField.setText(String.valueOf(patient.getZipCode()));
        emailJTextField.setText(patient.getEmailAddress());
        areaCodeJTextField.setText(String.valueOf(patient.getAreaCode()));
        numberJTextField.setText(String.valueOf(patient.getPhoneNumber()));
      
        nameJTextField.setEnabled(false);
        patientIDJTextField.setEnabled(false);
        ageJTextField.setEnabled(true);
        streetAddressJTextField.setEnabled(true);      
        cityJTextField.setEnabled(true);
        zipCodeJTextField.setEnabled(true);
        emailJTextField.setEnabled(true);
        areaCodeJTextField.setEnabled(true);
        numberJTextField.setEnabled(true);
        saveJButton.setEnabled(true);
        updateJButton.setEnabled(false);
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        if((ageJTextField.getText().length()==0)||
                (streetAddressJTextField.getText().length()==0)||
                (cityJTextField.getText().length()==0)||
                (zipCodeJTextField.getText().length()==0)||
                (emailJTextField.getText().length()==0)||
                (areaCodeJTextField.getText().length()==0)||
                (numberJTextField.getText().length()==0))
        {
            JOptionPane.showMessageDialog(null, "Alert! Inputs can not be empty! ", "Warning", JOptionPane.WARNING_MESSAGE); 
            
        } else {
            try {
            // Validate age - must be a number
            int age;
            try {
                age = Integer.parseInt(ageJTextField.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Age must be a number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate phone number - must be a number
            int phoneNumber;
            try {
                phoneNumber = Integer.parseInt(numberJTextField.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Phone Number must be a number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate email format - must contain '@' and end with '.com'
            String email = emailJTextField.getText();
            if (!email.contains("@") || !email.endsWith(".com")) {
                JOptionPane.showMessageDialog(null, "Email must be in the format: xxx@xxx.com", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate zip code - must be a number (no letters or symbols)
            String zipCodeText = zipCodeJTextField.getText();
            if (!zipCodeText.matches("\\d+")) { // Regular expression to check if it's a number
                JOptionPane.showMessageDialog(null, "Zip Code must only contain numbers.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int zipCode = Integer.parseInt(zipCodeText); // Safe to parse now

            // Validate that other fields only contain letters and spaces
            if (!streetAddressJTextField.getText().matches("[a-zA-Z0-9 ]+")) {
                JOptionPane.showMessageDialog(null, "Street Address must only contain letters, numbers, and spaces.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!cityJTextField.getText().matches("[a-zA-Z ]+")) {
                JOptionPane.showMessageDialog(null, "City/Town must only contain letters and spaces.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Retrieve and save the valid data
            String streetAddress = streetAddressJTextField.getText();
            String town = cityJTextField.getText();
            String emailAddress = emailJTextField.getText();
            int areaCode = Integer.parseInt(areaCodeJTextField.getText());

            // Update patient data
            patient.setAge(age);
            patient.setAreaCode(areaCode);
            patient.setEmailAddress(emailAddress);
            patient.setPhoneNumber(phoneNumber);
            patient.setStreetAddress(streetAddress);
            patient.setTown(town);
            patient.setZipCode(zipCode);

            JOptionPane.showMessageDialog(null, "Patient Information Updated Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Disable fields and buttons after saving
            saveJButton.setEnabled(false);
            updateJButton.setEnabled(true);
            ageJTextField.setEnabled(false);
            streetAddressJTextField.setEnabled(false);
            nameJTextField.setEnabled(false);
            patientIDJTextField.setEnabled(false);
            cityJTextField.setEnabled(false);
            zipCodeJTextField.setEnabled(false);
            emailJTextField.setEnabled(false);
            areaCodeJTextField.setEnabled(false);
            numberJTextField.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Alert! Please enter valid values!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void btnIntegrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegrateActionPerformed
        // TODO add your handling code here:
        PersonalInfo panel = new PersonalInfo(userProcessContainer,userAccount,patientOrganization,enterprise,ecoSystem);
        userProcessContainer.add("ViewInsurance", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnIntegrateActionPerformed

    public void resetFields(){
        
        ageJTextField.setText("");
        nameJTextField.setText("");
        streetAddressJTextField.setText("");
        cityJTextField.setText("");
        zipCodeJTextField.setText("");
        emailJTextField.setText("");
        areaCodeJTextField.setText("");
        numberJTextField.setText("");
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JTextField areaCodeJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnIntegrate;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField numberJTextField;
    private javax.swing.JTextField patientIDJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JTextField streetAddressJTextField;
    private javax.swing.JButton updateJButton;
    private javax.swing.JTextField zipCodeJTextField;
    // End of variables declaration//GEN-END:variables
}
