/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.InsuranceRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Insurance.Insurance;
import Business.Organization.InsuranceOrganization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import UserInterface.DoctorRole.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jiaye
 */
public class AddInsuranceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;    
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private InsuranceOrganization insuranceOrganization;
    private Insurance insurance;
    /**
     * Creates new form MakePrescriptionJPanel
     */
    public AddInsuranceJPanel(JPanel userProcessContainer,UserAccount userAccount, InsuranceOrganization insuranceOrganization, Enterprise enterprise,EcoSystem ecoSyste) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        this.insuranceOrganization = (InsuranceOrganization)insuranceOrganization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblinsName = new javax.swing.JLabel();
        lblinsType = new javax.swing.JLabel();
        lblinsHospital = new javax.swing.JLabel();
        lblinsCharge = new javax.swing.JLabel();
        txtinsName = new javax.swing.JTextField();
        txtinsType = new javax.swing.JTextField();
        txtinsHospital = new javax.swing.JTextField();
        txtinsCharge = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtptName = new javax.swing.JTextField();
        lblptName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 162, 204));
        setMaximumSize(new java.awt.Dimension(700, 410));
        setMinimumSize(new java.awt.Dimension(700, 410));
        setPreferredSize(new java.awt.Dimension(700, 410));

        lblinsName.setText("Insurance name");

        lblinsType.setText("Insurance type");

        lblinsHospital.setText("Hospital served");

        lblinsCharge.setText("Insurance charge");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        lblTitle.setText("Add Insurance");

        lblptName.setText("Patient name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnBack)
                        .addGap(135, 135, 135)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinsName)
                            .addComponent(lblinsType)
                            .addComponent(lblinsHospital)
                            .addComponent(lblinsCharge)
                            .addComponent(lblptName))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtptName)
                            .addComponent(txtinsName)
                            .addComponent(txtinsType)
                            .addComponent(txtinsHospital)
                            .addComponent(txtinsCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblptName))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtinsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblinsName))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblinsType)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblinsHospital)
                            .addComponent(txtinsHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblinsCharge)
                            .addComponent(txtinsCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtinsType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String ptName = txtptName.getText();
        String insName = txtinsName.getText();
        String insType = txtinsType.getText();
        String insHospital = txtinsHospital.getText();
        String insCharge = txtinsCharge.getText();
        
        if (ptName.isEmpty() || insName.isEmpty() || insType.isEmpty() || insHospital.isEmpty() || insCharge.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required.");
            return;
        }

        if (ptName.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Patient name cannot contain numbers.");
            return;
        }
        if (insName.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Insurance name cannot contain numbers.");
            return;
        }
        if (insType.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Insurance type cannot contain numbers.");
            return;
        }
        if (insHospital.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Insurance hospital cannot contain numbers.");
            return;
        }

        try {
            Double.parseDouble(insCharge); 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Insurance charge must be a valid number.");
            return;
        }

       
        insuranceOrganization.getInsuranceDirectory().addInsurance(ptName, insName, insType, insHospital, insCharge);
        
        txtptName.setText("");
        txtinsName.setText("");
        txtinsType.setText("");
        txtinsHospital.setText("");
        txtinsCharge.setText("");
        
        userProcessContainer.remove(this); // 移除當前頁面
        Component[] components = userProcessContainer.getComponents();
        for (Component component : components) {
            if (component instanceof InsuranceAgentWorkAreaJPanel) {
                InsuranceAgentWorkAreaJPanel previousPanel = (InsuranceAgentWorkAreaJPanel) component;
                previousPanel.populateTable(); // 調用上一頁的刷新方法
            }
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblinsCharge;
    private javax.swing.JLabel lblinsHospital;
    private javax.swing.JLabel lblinsName;
    private javax.swing.JLabel lblinsType;
    private javax.swing.JLabel lblptName;
    private javax.swing.JTextField txtinsCharge;
    private javax.swing.JTextField txtinsHospital;
    private javax.swing.JTextField txtinsName;
    private javax.swing.JTextField txtinsType;
    private javax.swing.JTextField txtptName;
    // End of variables declaration//GEN-END:variables

}
