/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CitizenManagerAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CitizenManagerOrganization;
import Business.Organization.Organization;
import Business.Organization.RegionalGovOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 *@author Irene, Yushan
 */
public class CitizenManagerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private CitizenManagerOrganization organization;
    private EcoSystem ecoSystem;
    /**
     * Creates new form DrugSalesWorkAreaJPanel
     */
    public CitizenManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CitizenManagerOrganization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = (CitizenManagerOrganization)organization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        
    }
    
    private RegionalGovOrganization getGovernmentOrganization(ArrayList<Network> myNetwork) {
        for(Network network : myNetwork){
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    // Check if the organization is a Government Organization
                    if (organization instanceof RegionalGovOrganization) {
                        return (RegionalGovOrganization) organization;
                    }
                }
            }
        }
        // Return null if no Government Organization is found
        return null;
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblCitizen.getModel();    
        model.setRowCount(0);
        
        // Retrieve all enterprises from the EcoSystem
        ArrayList<Network> networkList = ecoSystem.getNetworkList();
        
        RegionalGovOrganization myGovernmentOrganization = getGovernmentOrganization(networkList);

        // Get all user accounts
        ArrayList<UserAccount> allUserAccounts = myGovernmentOrganization.getAllUserAccounts(networkList);

        // Populate the table
        for (UserAccount userAccount : allUserAccounts) {
            Object[] row = new Object[2];
            row[0] = userAccount.getName();  // name
            row[1] = userAccount.getId();      

            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCitizen = new javax.swing.JTable();
        btnInfo = new javax.swing.JButton();

        setBackground(new java.awt.Color(253, 226, 185));
        setMinimumSize(new java.awt.Dimension(700, 410));
        setPreferredSize(new java.awt.Dimension(700, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel12.setText("Citizen Manager Work Area");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 350, -1));

        tblCitizen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person Name", "Person ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCitizen);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 500, 340));

        btnInfo.setText("Request info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCitizen;
    // End of variables declaration//GEN-END:variables
}
